### PR TITLE
adds some basic evaluation tests

### PR DESCRIPTION
**Pull request by alexshadley**
Super basic PR, just adds a couple tests for evaluation.  We should definitely extend this as we go.

### CODE REVIEW

**Review by EmiliaPaz — CHANGES_REQUESTED** [review]
These test are good and pretty self-explanatory. As you said, definitely we can extend as we go. We could add boolean expressions before we merge since they are working.

**Comment by brianquiroz216** [comment]
The tests look good! I added a couple tests for lambda functions.

**Review by brian-quiroz — COMMENTED** [review]
The tests look good! I added a couple tests for lambda functions.

**Comment by alexshadley** [comment]
Alrighty, I went ahead and commented out the function tests for now (they look good, it's just that they won't compile until we merge lambdas in).  We can uncomment as soon as those changes make it to master.  I also added a couple boolean tests.

**Pull request merged**
